# Generated by Django 5.2.15 on 2026-06-26 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_intern_schedule_permissions(apps, schema_editor):
    Feature = apps.get_model('dashboard', 'Feature')
    FeatureAccess = apps.get_model('dashboard', 'FeatureAccess')
    feature, _ = Feature.objects.update_or_create(
        key='interns',
        defaults={
            'name': '实习生登记',
            'url_name': 'dashboard:interns',
            'sort_order': 70,
            'is_active': True,
        },
    )
    access = {
        'super_admin': {'view', 'use', 'manage'},
        'team_lead': {'view', 'use'},
        'member': {'view', 'use'},
        'intern': {'view', 'use'},
        'anonymous': set(),
    }
    for role, allowed_actions in access.items():
        for action in ['view', 'use', 'manage']:
            FeatureAccess.objects.update_or_create(
                feature=feature,
                role=role,
                action=action,
                defaults={'allowed': action in allowed_actions},
            )


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_type', models.CharField(choices=[('work', '工作安排'), ('leave', '请假')], default='work', max_length=20, verbose_name='类型')),
                ('title', models.CharField(max_length=120, verbose_name='工作标题')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_intern_schedules', to=settings.AUTH_USER_MODEL, verbose_name='安排人')),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intern_schedules', to=settings.AUTH_USER_MODEL, verbose_name='实习生')),
            ],
            options={
                'verbose_name': '实习生工作安排',
                'verbose_name_plural': '实习生工作安排',
                'ordering': ['start_time', 'id'],
            },
        ),
        migrations.RunPython(seed_intern_schedule_permissions, migrations.RunPython.noop),
    ]
