# Generated by Django 5.2.15 on 2026-06-26 09:17

import dashboard.models
import django.db.models.deletion
from django.db import migrations, models


def migrate_user_interns_to_profiles(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Group = apps.get_model('auth', 'Group')
    Intern = apps.get_model('dashboard', 'Intern')
    InternSchedule = apps.get_model('dashboard', 'InternSchedule')

    user_ids = set(InternSchedule.objects.values_list('intern_id', flat=True))
    try:
        intern_group = Group.objects.get(name='实习生')
        user_ids.update(User.objects.filter(groups=intern_group).values_list('id', flat=True))
    except Group.DoesNotExist:
        pass

    for user in User.objects.filter(id__in=user_ids):
        name = user.get_full_name().strip() or user.get_username()
        Intern.objects.update_or_create(
            id=user.id,
            defaults={
                'name': name,
                'note': f'由旧实习生用户 {user.get_username()} 迁移',
                'is_active': True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_sync_permission_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='姓名')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('access_token', models.CharField(default=dashboard.models.make_intern_access_token, max_length=80, unique=True, verbose_name='专属链接令牌')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '实习生',
                'verbose_name_plural': '实习生',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.RunPython(migrate_user_interns_to_profiles, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='internschedule',
            name='intern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intern_schedules', to='dashboard.intern', verbose_name='实习生'),
        ),
    ]
