# Generated by Django 5.2.15 on 2026-07-02 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_commonwebsitesetting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='标题')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('is_restricted', models.BooleanField(default=False, verbose_name='仅指定用户可见')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '常用信息卡片',
                'verbose_name_plural': '常用信息卡片',
                'ordering': ['sort_order', 'title', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InfoCardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=120, verbose_name='键')),
                ('value', models.TextField(verbose_name='值')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='排序')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dashboard.infocard', verbose_name='卡片')),
            ],
            options={
                'verbose_name': '常用信息条目',
                'verbose_name_plural': '常用信息条目',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InfoCardPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='dashboard.infocard', verbose_name='卡片')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permitted_info_cards', to=settings.AUTH_USER_MODEL, verbose_name='可见用户')),
            ],
            options={
                'verbose_name': '常用信息卡片权限',
                'verbose_name_plural': '常用信息卡片权限',
                'ordering': ['card__sort_order', 'user__username'],
                'unique_together': {('card', 'user')},
            },
        ),
        migrations.CreateModel(
            name='InfoCardSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='default', max_length=40, unique=True)),
                ('cards_per_row', models.PositiveSmallIntegerField(default=3, verbose_name='每行卡片数')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '常用信息设置',
                'verbose_name_plural': '常用信息设置',
                'ordering': ['key'],
            },
        ),
    ]
