# Generated by Django 5.2.15 on 2026-06-28 07:21

import csv
import json
from pathlib import Path

from django.db import migrations, models


def _read_json(path, default):
    if not path.exists():
        return default
    try:
        with path.open('r', encoding='utf-8') as source:
            return json.load(source)
    except Exception:
        return default


def _read_csv_rows(path):
    if not path.exists():
        return [], []
    for encoding in ['utf-8-sig', 'gbk']:
        try:
            with path.open('r', encoding=encoding, newline='') as source:
                reader = csv.DictReader(source)
                columns = [str(column).strip().replace('\n', '') for column in (reader.fieldnames or [])]
                rows = []
                for row in reader:
                    rows.append({column: str(row.get(column, '') or '') for column in columns})
                return columns, rows
        except UnicodeDecodeError:
            continue
    return [], []


def import_existing_files(apps, schema_editor):
    store_model = apps.get_model('bondreminder', 'BondReminderStore')
    row_model = apps.get_model('bondreminder', 'BondReminderTableRow')
    bond_root = Path(__file__).resolve().parents[2]
    data_dir = bond_root / 'data'

    json_files = [
        ('config', data_dir / 'config.json', {}),
        ('contacts', data_dir / 'contacts.json', []),
        ('customer_settings', data_dir / 'customer_settings.json', {}),
    ]
    for key, path, default in json_files:
        value = _read_json(path, default)
        store_model.objects.update_or_create(key=key, defaults={'value': value})

    customer_data = _read_json(data_dir / 'customer_data.json', {'columns': [], 'rows': []})
    customer_columns = [str(column).strip() for column in customer_data.get('columns', [])]
    customer_rows = customer_data.get('rows', []) if isinstance(customer_data, dict) else []
    store_model.objects.update_or_create(
        key='customer_table_meta',
        defaults={'value': {'columns': customer_columns, 'total_rows': len(customer_rows), 'source_path': 'customer_data.json'}},
    )
    for index, row in enumerate(customer_rows):
        row_model.objects.update_or_create(
            table_key='customer',
            row_index=index,
            defaults={'data': {column: str(row.get(column, '') or '') for column in customer_columns}},
        )

    bond_path = data_dir / 'bond_data_cache.csv'
    bond_columns, bond_rows = _read_csv_rows(bond_path)
    store_model.objects.update_or_create(
        key='bond_table_meta',
        defaults={'value': {'columns': bond_columns, 'total_rows': len(bond_rows), 'source_path': str(bond_path)}},
    )
    for index, row in enumerate(bond_rows):
        row_model.objects.update_or_create(
            table_key='bond',
            row_index=index,
            defaults={'data': row},
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BondReminderStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80, unique=True, verbose_name='数据键')),
                ('value', models.JSONField(blank=True, default=dict, verbose_name='数据内容')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '付息兑付配置数据',
                'verbose_name_plural': '付息兑付配置数据',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='BondReminderTableRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_key', models.CharField(choices=[('bond', '付息兑付表'), ('customer', '客户表')], max_length=40, verbose_name='表类型')),
                ('row_index', models.PositiveIntegerField(verbose_name='行号')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='行数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '付息兑付表格行',
                'verbose_name_plural': '付息兑付表格行',
                'ordering': ['table_key', 'row_index'],
                'unique_together': {('table_key', 'row_index')},
            },
        ),
        migrations.RunPython(import_existing_files, migrations.RunPython.noop),
    ]
