# Generated by Django 5.2.15 on 2026-06-28 07:21

from django.db import migrations, models


def initialize_latest_store(apps, schema_editor):
    store_model = apps.get_model('bondreminder', 'BondReminderStore')
    defaults = [
        ('config', {}),
        ('contacts', []),
        ('customer_settings', {}),
        ('bond_table_meta', {'columns': [], 'total_rows': 0, 'source_path': ''}),
        ('customer_table_meta', {'columns': [], 'total_rows': 0, 'source_path': ''}),
    ]
    for key, value in defaults:
        store_model.objects.update_or_create(key=key, defaults={'value': value})


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BondReminderStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80, unique=True, verbose_name='数据键')),
                ('value', models.JSONField(blank=True, default=dict, verbose_name='数据内容')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '付息兑付配置数据',
                'verbose_name_plural': '付息兑付配置数据',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='BondReminderTableRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_key', models.CharField(choices=[('bond', '付息兑付表'), ('customer', '客户表')], max_length=40, verbose_name='表类型')),
                ('row_index', models.PositiveIntegerField(verbose_name='行号')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='行数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '付息兑付表格行',
                'verbose_name_plural': '付息兑付表格行',
                'ordering': ['table_key', 'row_index'],
                'unique_together': {('table_key', 'row_index')},
            },
        ),
        migrations.RunPython(initialize_latest_store, migrations.RunPython.noop),
    ]
