# Generated by Codex on 2026-06-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bondreminder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BondReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.TextField(verbose_name='运行日志')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '付息兑付运行日志',
                'verbose_name_plural': '付息兑付运行日志',
                'ordering': ['id'],
            },
        ),
    ]
